version: "3.7"

# NOTE: Run `docker-compose up --build` to rebuild and relaunch containers

services:

    mysql:
        build: ./mysql
        container_name: mysql

        restart: always

        env_file:
            - ./.env

        environment:
            - MYSQL_DATABASE=portal-data
            - MYSQL_ROOT_PASSWORD=pass

        expose:
            - 3306

    portal:
        build: ./portal
        container_name: portal
        depends_on:
            - mysql

        restart: always

        env_file:
            - ./.env

        environment:
            # Override any other settings to use the MySQL database
            - FLASK_SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:pass@mysql:3306/portal-data

        # Port 8000 is only used by nginx as a reverse proxy
        # this should not be accessible outside of localhost
        expose:
            - 8000

    nginx:
        build: ./nginx
        container_name: nginx

        restart: always

        # Map both HTTP and HTTPS from host to container
        ports:
            - 80:80
            - 443:443
