version: "3.7"

# NOTE: Run `docker-compose up --build` to rebuild and relaunch containers

services:

    # Disable the 'mysql' service if using alternative database management system.
    # Make sure you change the FLASK_SQLALCHEMY_DATABASE_URI to match the active database
    mysql:
        container_name: mysql
        env_file: ./.env
        build: ./mysql

        restart: always

        environment:
            - MYSQL_DATABASE=portal-data
            - MYSQL_ROOT_PASSWORD=pass

        expose:
            - 3306

    portal:
        container_name: portal
        env_file: ./.env
        build: ./portal

        # This starts the service after mysql service, however database
        # may still not be initialized, so need a connect-retry loop to ensure
        # that the connection was successful.
        depends_on:
            - mysql

        restart: always

        environment:
            # Override any other settings to use the MySQL database
            - FLASK_SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:pass@mysql:3306/portal-data

        # Port 8000 is only used by nginx as a reverse proxy
        # this should not be accessible outside of localhost
        expose:
            - 8000

    nginx:
        container_name: nginx
        env_file: ./.env

        build:
            context: ./nginx
            args:
                - CERT_COUNTRY=${CERT_COUNTRY}
                - CERT_STATE=${CERT_STATE}
                - CERT_LOC=${CERT_LOC}
                - CERT_ORG=${CERT_ORG}
                - CERT_ORGUNIT=${CERT_ORGUNIT}
                - SERVER_NAME=${FLASK_SERVER_NAME}

        restart: always

        # Map both HTTP and HTTPS from host to container
        ports:
            - 80:80
            - 443:443
