name: Python tests

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
permissions:
    contents: read
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python 3.11.2
              uses: actions/setup-python@v3
              with:
                  python-version: "3.11.2"
            - name: Install dependencies
              working-directory: portal
              run: |
                  python -m pip install --upgrade pip
                  pip install flake8 pytest
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - name: Lint with flake8
              working-directory: portal
              run: |
                  # stop the build if there are Python syntax errors or undefined names
                  flake8 app --count --select=E9,F63,F7,F82 --show-source --statistics
                  # exit-zero treats all errors as warnings.
                  flake8 app --count --statistics
            - name: Test with pytest
              working-directory: portal
              run: |
                  pytest
